[package]
name = "ikev2"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
bitflags = "2.9.1"
bytemuck = { version = "1.25.0", features = ["derive"] }
bytes = "1.10.1"
futures = "0.3.32"
futures-timer = "3.0.3"
hex = "0.4.3"
hex-literal = "1.1.0"
log = "0.4.28"
openssl = { version = "0.10.75" }
phf = { version = "0.13.1", features = ["macros"] }
rend = { version = "0.5.2", features = ["bytemuck-1"] }
ring = "0.17.14"
rustls = { version = "0.23.37", default-features = false, features = ["std", "tls12", "ring"] }
rustls-pki-types = "1.12.0"
rustls-webpki = { version = "0.103.9", features = ["ring"] }

# crypto

[dev-dependencies]
hex = "0.4.3"
